version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "db-logs"
      MONGO_INITDB_ROOT_USERNAME: "go-admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    volumes:
      - ./db-data/mongo/:/data/db

  